Add `CountryCodeDataList` view helper and `CountryCode` validator
laminas/laminas-i18n pull request #86
Opened 2022-09-13 16:20 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | not yet - required
| New Feature   | yes
| RFC           | no?

### Description

Given the addition of the country code value object in #84, this patch puts it to use by adding a list object available in the container, that users can use to retrieve a list of all ISO-3166 alpha 2 country codes. The list implements and is aliased to a simple interface that user can override in the container, for example, in order to restrict the list to desired countries.

A view helper is added that outputs an HTML `datalist` element, useful for autocomplete and a validator for ISO3166 country codes.

Documentation is outstanding.

2022-09-13 16:27 UTC, Ocramius reviewed
Partial review - dropping in some feedback though :-)

2022-09-13 16:27 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +        'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW',
Let's please have these one-per-line instead of in this format - it's a mess to diff otherwise, when something shifts.

2022-09-13 16:27 UTC, Ocramius commented on src/ConfigProvider.php
> +     * @return array<string, ServiceManagerConfigurationType|mixed>
This `|mixed` is a bit of a mess :thinking: 

Can it be avoided?

2022-09-13 16:27 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +     * @psalm-var list<non-empty-string>
`non-empty-list`

2022-09-13 16:27 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +    /** @return list<CountryCode> */
`non-empty-list`

2022-09-13 16:27 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +    /** @var list<CountryCode>|null */
I don't think it's worth caching this in memory, is it? :thinking:

2022-09-13 16:27 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +    public function count(): int
`positive-int`

2022-09-13 16:27 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +    /** @return list<CountryCode> */
`non-empty-list`

2022-09-13 16:38 UTC, gsteel commented on src/ConfigProvider.php
> +     * @return array<string, ServiceManagerConfigurationType|mixed>
I added `'locale' => null` to the top-level array, previously, it only returned SM related config. Not sure if I can be more specific than mixed?

2022-09-13 16:39 UTC, gsteel commented
> Partial review - dropping in some feedback though

Thanks @Ocramius

2022-09-14 18:47 UTC, Ocramius commented on src/Geography/CountryCodeListInterface.php
> +interface CountryCodeListInterface extends IteratorAggregate, Countable
Uhhh, do we need a custom iterator interface for this? Doesn't a well typed generator work?

2022-09-14 18:47 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +final class DefaultCountryCodeList implements CountryCodeListInterface
I would implement `Countable` and `IteratorAggregate` here, rather than `CountryCodeListInterface` :thinking:

2022-09-14 18:47 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +                assert($code !== '');
Instead of this, you can annotate the closure to accept `/** @param non-empty-string $code */`

Alternatively, `array_map([CountryCode::class, 'fromString'], self::LIST)`, which should also work

2022-09-14 18:47 UTC, Ocramius commented on src/Geography/DefaultCountryCodeListFactory.php
> +        return DefaultCountryCodeList::create();
Instead of declaring the factory, can we have the country code list use `[DefaultCountryCodeList::class, 'create']` in the service bindings? :thinking:

2022-09-14 18:47 UTC, Ocramius commented on src/View/Helper/CountryCodeDataList.php
> +            (string) $attributes,
Let's use `->__toString()`, if really needed :)

2022-09-14 19:33 UTC, gsteel commented on src/Geography/DefaultCountryCodeList.php
> +                assert($code !== '');
You're absolutely right of course, but I can't get rid of the `ArgumentTypeCoercion` any way I do it. Even the \@param annotation doesn't work 🤷‍♂️ I think there might be some kind of max size issue with the array: https://psalm.dev/r/e43f53fe65

Interestingly, the `[InvalidConstantAssignmentValue](https://psalm.dev/304)` issue does not appear for me locally.

2022-09-14 19:38 UTC, gsteel commented on src/Geography/CountryCodeListInterface.php
> +interface CountryCodeListInterface extends IteratorAggregate, Countable
The plan here is to allow users to substitute their own list. The shipped list is immutable. From a validation, or form element perspective, users may want to limit valid values to a specific subset. To be fair, we could just get rid of the list completely and require `list<CountryCode>` adding a static method such as `CountryCode::iso3166List(): list<CountryCode>`

2022-10-10 15:50 UTC, Ocramius approved these changes
IMO this is good to go, @gsteel!

Do we need to add docs for it, though? :thinking:

2022-10-10 15:50 UTC, Ocramius commented on src/ConfigProvider.php
> +     * @return array<string, ServiceManagerConfigurationType|mixed>
Good as-is

2022-10-10 15:51 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +final class DefaultCountryCodeList implements CountryCodeListInterface
Discussed above: the iterable interface is needed on the interface itself.

2022-10-10 15:51 UTC, Ocramius commented on src/Geography/DefaultCountryCodeList.php
> +                assert($code !== '');
Good as-is :+1:

2022-10-10 15:52 UTC, Ocramius commented
Clearing milestone for a release meanwhile: will re-target `2.20.x`

2022-10-10 16:00 UTC, gsteel commented
I'll get some docs together for review by @froschdesign soon as I can :)

2022-12-02 16:25 UTC, gsteel commented
Current psalm issues are unrelated - service manager needs an update so I'll do that in another patch

2022-12-16 09:11 UTC, froschdesign requested changes
Good work! 👍🏻 

Only a few minor changes are needed.

2022-12-16 09:11 UTC, froschdesign commented on docs/book/validators/country-code.md
> +**known and valid** ISO-3166 alpha 2 country code.
"ISO-3166 alpha-2" or "ISO-3166-1 alpha-2"?

```suggestion
`Laminas\I18n\Validator\CountryCode` allows you to validate if a given value is **known and valid** two-letter country codes of [ISO-3166 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
```

2022-12-16 09:11 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +The `CountryCodeDataList` view helper can be used to render an HTML [&lt;datalist&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) element containing a list of ISO-3166 countr
```suggestion
The `CountryCodeDataList` view helper can be used to render an HTML [&lt;datalist&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) element containing a list of ISO-3166 country codes with two-letter country codes and localised country names.
```

2022-12-16 09:11 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +The helper's constructor accepts an object that implements `Laminas\I18n\Geography\CountryCodeListInterface`. This interface has no specific methods other than those it inherits from [`IteratorAggreg
One sentence per-line:

```suggestion
The helper's constructor accepts an object that implements `Laminas\I18n\Geography\CountryCodeListInterface`.
This interface has no specific methods other than those it inherits from [`IteratorAggregate`](https://www.php.net/manual/en/class.iteratoraggregate.php) and [`Countable`](https://www.php.net/manual/en/class.countable.php).
This object must be an iterable that yields a list of `Laminas\I18n\CountryCode` value objects.
```

2022-12-16 09:11 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +In order to inject the list into the helper, you can setup a factory that replaces the view helpers default factory:
A path and a file name must be added here as an example. Otherwise the reader does not know where the factory class can be placed.

### Filenames

A filename must be placed before a code example because there are always two parts for this information: 

1. what kind of file is this
2. and what is the name or path.

Both informations in a code comment would be too long and misplaced.

#### Examples

> Create a file for the module configuration called `module.config.php` under `laminas-mvc-tutorial/module/Album/config/`:

> …in a factory, e.g. `src/Album/Controller/AlbumControllerFactory.php`:

> …in a module configuration file, e.g. `module/ExampleModule/config/module.config.php`:

2022-12-16 09:11 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +You would then configure your application config to register this factory for the helper:
Add a filename and path also here.

2022-12-16 09:11 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +Assuming your customised list is available in the DI container with the alias `MyCountryList`, modify your application configuration so that the list interface is aliased to your own implementation:
Add a filename and path also here.

2022-12-16 09:49 UTC, froschdesign commented on docs/book/validators/country-code.md
> +**known and valid** ISO-3166 alpha 2 country code.
@gsteel 
What is meant here or what is the exact term? "ISO-3166 alpha-2" or "ISO-3166-1 alpha-2"?

2022-12-16 10:03 UTC, gsteel commented on docs/book/validators/country-code.md
> +**known and valid** ISO-3166 alpha 2 country code.
Country codes are 3166-1, 3166-2 are regional subdivisions and 3166-3 are country codes deleted from 3166-1.

Within 3166-1, there are alpha-2, alpha-3 and numeric codes for each country.

It's more precise to state 3166-1 but I feel like the link helps with any perceived ambiguity??

2022-12-16 10:08 UTC, froschdesign requested changes

2022-12-16 10:08 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +For example, in a Laminas MVC module, the file might be `module/MyModule/config/module.config.php`
The package name is the preferred way so far:

```suggestion
For example, in a laminas-mvc module, the file might be `module/MyModule/config/module.config.php`
```

(If something refers to Mezzio, then the spelling with a capital initial is used: "Mezzio". The package names also follow the names used in Composer. Example: "mezzio-problem-details".)

2022-12-16 10:08 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +Example configuration file path for a Laminas MVC module: `module/MyModule/config/module.config.php`
```suggestion
Example configuration file path for a laminas-mvc module: `module/MyModule/config/module.config.php`
```

2022-12-16 10:08 UTC, froschdesign commented on docs/book/view-helpers/country-code-data-list.md
> +     * 'service_manager' is the key used in a Laminas MVC application.
```suggestion
     * 'service_manager' is the key used in a laminas-mvc application.
```

2022-12-16 10:09 UTC, froschdesign commented on docs/book/validators/country-code.md
> +**known and valid** ISO-3166 alpha 2 country code.
> It's more precise to state 3166-1 but I feel like the link helps with any perceived ambiguity??

"ISO-3166 alpha-2" is okay then. 👍🏻

2022-12-16 11:15 UTC, froschdesign commented
@gsteel 
One last step: add the new validator and view helper to the MkDocs configuration file.

https://github.com/laminas/laminas-i18n/blob/fa9fc18a74c0c4ee14b9f72088e1bacc0820d945/mkdocs.yml#L20-L36

Thanks in advance! 👍🏻

2022-12-16 11:58 UTC, gsteel commented
Thanks for the help @froschdesign 👍

2022-12-16 12:00 UTC, froschdesign approved these changes

2022-12-16 12:28 UTC, merged